import Head from 'next/head'
import "@fontsource/inter"; // Defaults to weight 400.
import { BsPauseFill, BsPlayFill, BsStopFill } from 'react-icons/bs'
import useStore from '../util/useStore';
//col 1 #1d1d42  col 2 #26264e
export default function Home() {
  const { play, setPlay, setFinished } = useStore()
  return (
    <div className='p-2 bg-[#101010] w-screen min-h-screen text-white relative overflow-x-hidden'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' opacity-0 py-2 font-extrabold text-transparent text-6xl bg-clip-text bg-gradient-to-tr text-center uppercase from-purple-600 to-pink-500'>
        Spellify
      </div>
      <div className='w-full my-16 flex items-center justify-center absolute bottom-0 left-0'>
        <button onClick={() => {
          setPlay()
          setFinished()
        }} className='w-16 h-16 rounded-full flex items-center justify-center bg-zinc-900 '>
        </button>
      </div>
    </div>
  )
}
